### ISSUE TITLE
Provide namespace support

### ISSUE THREAD

**Issue by doompadee** [BrandonXLF/c-minor#2]
Nice helper! The main thing missing for me, is namespace support. My main use case would be creating svg elements, which requires `createElementNS` instead of `createElement`.

```javascript
c(
  'svg',
  { class: 'fill-current size-5 cursor-pointer' },
  c(
    'use',
    { href: `#backIcon` }
  )
)
```

Maybe in similar vain as the attribute prefixes, the namespace could be provided as a suffix:

```javascript
c(
  'svg@http://www.w3.org/2000/svg', // or maybe 'http://www.w3.org/2000/svg::svg'?
  { class: 'fill-current size-5 cursor-pointer' },
  c(
    'use@http://www.w3.org/2000/svg',
    { href: `#backIcon` }
  )
)
```

To remedy the need to provide the full namespace each time, mappings of some common ones (svg, mathml) could be build-in:

```javascript
c(
  'svg::svg',
  { class: 'fill-current size-5 cursor-pointer' },
  c(
    'svg::use',
    { href: `#backIcon` }
  )
)
```

**Comment by BrandonXLF** [comment]
@doompadee Thanks! I implemented the "@" syntax with the full namespace name as of version 1.4.0.
